# Generated by Django 5.1.4 on 2026-09-27 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Payment pending'), ('CONFIRMED', 'Awaiting arrival'), ('FAILED', 'Payment failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Test completed'), ('NO_SHOW', 'Did not arrive'), ('REPORT_DELIVERED', 'Report delivered')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Payment pending'), ('CONFIRMED', 'Awaiting arrival'), ('FAILED', 'Payment failed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Test completed'), ('NO_SHOW', 'Did not arrive'), ('REPORT_DELIVERED', 'Report delivered')], max_length=20)),
                ('actor_role', models.CharField(choices=[('CLIENT', 'Client'), ('CENTRE', 'Centre'), ('LAB', 'Lab'), ('PLATFORM_ADMIN', 'Platform Admin'), ('SYSTEM', 'System')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='bookings.booking')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
