# Generated by Django 5.1.4 on 2026-09-27 07:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_test_centretest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='transaction_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
