# Generated by Django 5.1.4 on 2026-09-27 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_lab_transaction_fee_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0 = Monday', null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to='catalog.centre')),
            ],
            options={
                'ordering': ['weekday', 'date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('weekday__isnull', False)), models.Q(('date__isnull', False), ('weekday__isnull', True)), _connector='OR'), name='slot_rule_weekday_xor_date'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='slot_rule_end_after_start')],
            },
        ),
    ]
