# Generated by Django 5.1.4 on 2026-09-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('INSUFFICIENT_FUNDS', 'Insufficient funds'), ('CARD_DECLINED', 'Declined by the issuing bank'), ('INCORRECT_PIN', 'Incorrect PIN or OTP'), ('AUTHENTICATION_FAILED', 'Authentication not completed'), ('BANK_UNAVAILABLE', 'Bank server unavailable'), ('TIMED_OUT', 'Payment request timed out')], max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
